[package.metadata.clippy]
warns = []
allow_clippy_lints = [
    "non_snake_case",
    "non_camel_case_types",
    "upper_case_acronyms",
]
[package]
name = "RustBinTemplateForCamel"
version = "0.1.0"
edition = "2024"

[dependencies]
